beta:
- gas_scale
- gas_index
- gas_norm
doublebeta:
- gas_scale
- gas_index
- gas_norm
- gas_scale2
- gas_index2
- gas_norm2
exp:
- gas_scale
- gas_norm
powerlaw:
- gas_scale
- gas_index
- gas_norm
flat:
- gas_norm
