beta:
- scale
- index
- gas_norm
doublebeta:
- scale
- index
- gas_norm
- scale2
- index2
- gas_norm2
exp:
- scale
- gas_norm
powerlaw:
- scale
- index
- gas_norm
flat:
- gas_norm
