beta:
- mag_norm
- scale
- index
doublebeta:
- mag_norm
- scale
- index
- mag_norm2
- scale2
- index2
exp:
- scale
- mag_norm
flat:
- mag_norm
m31:
- scale
- mag_norm
pl:
- scale
- index
- mag_norm
