angle:
- calc_angmax_integrate
density:
- halo_norm
distance:
- halo_distance
- halo_scale
- halo_rvir
- mag_scale
- mag_scale2
- gas_scale
- gas_scale2
- calc_rmax_integrate
- diff_rmax
- coherence_scale
- halo_core_scale
- green_averaging_scale
time:
- adi_delta_ti
- adi_delta_t_min
energy:
- m_wimp
- e_sample_min
frequency:
- f_sample_limits
- f_sample_values
j_factor:
- halo_j_factor
d_factor:
- halo_d_factor
magnetic:
- mag_norm
- mag_norm2
- mag_field_average
mass:
- halo_mvir
num_density:
- gas_norm
- gas_norm2
- gas_average_density
energy_density:
- photon_density
diff_constant:
- diff_constant
cross_section:
- cross_section
decay_rate:
- decay_rate
temperature:
- photon_temp