angle:
- calcAngmaxIntegrate
density:
- haloNorm
distance:
- haloDistance
- haloScale
- haloRvir
- magScale
- magScale2
- gasScale
- gasScale2
- calcRmaxIntegrate
- calcRmax
- coherenceScale
- haloCoreScale
time:
- crankDeltaTi
- crankDeltaTMin
energy:
- mWIMP
- eSampleMin
frequency:
- fSampleLimits
- fSampleValues
jFactor:
- haloJFactor
dFactor:
- haloDFactor
magnetic:
- magNorm
- magNorm2
mass:
- haloMvir
numDensity:
- gasNorm
- gasNorm2
diffConstant:
- diffConstant
crossSection:
- crossSection
decayRate:
- decayRate
