angle:
- angmax_integrate
density:
- rho_norm
distance:
- distance
- scale
- rvir
- scale2
- rmax_integrate
- diff_rmax
- coherence_scale
- core_scale
- green_averaging_scale
- truncation_scale
time:
- adi_delta_ti
- adi_delta_t_min
energy:
- m_wimp
- e_sample_min
frequency:
- f_sample_limits
- f_sample_values
j_factor:
- j_factor
d_factor:
- d_factor
magnetic:
- mag_norm
- mag_norm2
- mag_field_average
mass:
- mvir
num_density:
- gas_norm
- gas_norm2
- gas_average_density
energy_density:
- photon_density
diff_constant:
- diff_constant
cross_section:
- cross_section
decay_rate:
- decay_rate
temperature:
- photon_temp